allowBuilds:
  '@anthropic-ai/claude-code': true
  '@github/keytar': false
  node-pty: false
minimumReleaseAgeExclude:
  - '@anthropic-ai/claude-code-darwin-arm64@2.1.237'
  - '@anthropic-ai/claude-code-darwin-x64@2.1.237'
  - '@anthropic-ai/claude-code-linux-arm64-musl@2.1.237'
  - '@anthropic-ai/claude-code-linux-arm64@2.1.237'
  - '@anthropic-ai/claude-code-linux-x64-musl@2.1.237'
  - '@anthropic-ai/claude-code-linux-x64@2.1.237'
  - '@anthropic-ai/claude-code-win32-arm64@2.1.237'
  - '@anthropic-ai/claude-code-win32-x64@2.1.237'
  - '@anthropic-ai/claude-code@2.1.237'
  - '@google/gemini-cli@0.56.0'
